### ISSUE TITLE
UE4JoystickPlugin issue

### ISSUE THREAD

**Issue by jvukovich** [tsky1971/CG221Connector#1]
Could you turn issues on over at https://github.com/tsky1971/UEJoystickPlugin ? I'd like to report a problem, but it looks like issues are disabled.

The HAT UP on my joystick gets "stuck". It doesn't release. It seems to happen randomly. All other hat movement works fine, just UP gets stuck.

It doesn't happen in other games. I play Descent regularly (online) and it uses SDL; no issues with the stick getting stuck. Seems to be an issue with the plugin.

**Comment by tsky1971** [comment]
Issues turned on. May be it take some time to inspect this error by me.
