### ISSUE TITLE
Any chance update plugin for UE 4.21

### ISSUE THREAD

**Issue by zek0** [tsky1971/CG221Connector#2]
Any chance update TrackIR plugin for UE 4.21.

Thank you!

**Comment by tsky1971** [comment]
Hi,
the project is now running with 4.21. 

Keep in mind: without the SDK Source from TrackIR the Project is not very useful for you. the are no stuff at all in the project which gets data from an trackir device nor the Service-Tool from TrackIR.

I created an small app which redirects the TrackIR data to the plugin. This is the "usecase" in my lab. UDP and OSC where only a small research project.

t.
